
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MITRegistration.java
 *
 * Created on Jul 11, 2013, 7:13:06 PM
 */
/**
 *
 * @author Linons
 */
public class MITRegistration extends javax.swing.JFrame {
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /** Creates new form MITRegistration */
    public MITRegistration() {
        initComponents();
        
        conn=dbconnection.ConnecrDb();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        yrlevel = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        section = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cpnum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MIT Registration By : John Colin A. Castino");
        setMinimumSize(new java.awt.Dimension(1280, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48));
        jLabel1.setText("First Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48));
        jLabel2.setText("Last Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 11, -1, -1));

        fname.setFont(new java.awt.Font("Tahoma", 0, 36));
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 366, -1));

        lname.setFont(new java.awt.Font("Tahoma", 0, 36));
        jPanel1.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 338, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48));
        jLabel3.setText("Year Level");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        yrlevel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        yrlevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grade 8", "2nd Year", "3rd Year", "4th Year" }));
        jPanel1.add(yrlevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 200, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48));
        jLabel4.setText("Section");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, -1, -1));

        section.setFont(new java.awt.Font("Tahoma", 0, 36));
        jPanel1.add(section, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 170, 300, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 48));
        jLabel5.setText("CP #");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        cpnum.setFont(new java.awt.Font("Tahoma", 0, 36));
        jPanel1.add(cpnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 240, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 48));
        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, -1, -1));

        email.setFont(new java.awt.Font("Tahoma", 0, 36));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, 310, -1));

        jButton1.setFont(new java.awt.Font("Liquid Crystal", 0, 70));
        jButton1.setText("REGISTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, 420, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoF.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
            
            String sql ="Insert into Members (FirstName,LastName,YearLevel,Section,CPNumber,Email) values(?,?,?,?,?,?)";
            
            pst=conn.prepareStatement(sql);
            
            
            pst.setString(1, fname.getText());
            pst.setString(2, lname.getText());
            String yl = yrlevel.getSelectedItem().toString();
            pst.setString(3, yl);
            pst.setString(4, section.getText());
            pst.setString(5, cpnum.getText());
            pst.setString(6, email.getText());
            
            
            
            
            
            
            
            
            
            
            
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "REGISTERED");
            fname.setText("");
            lname.setText("");
            section.setText("");
            cpnum.setText("");
            email.setText("");

        }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MITRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MITRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MITRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MITRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MITRegistration().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpnum;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField section;
    private javax.swing.JComboBox yrlevel;
    // End of variables declaration//GEN-END:variables
}
